Module1 task1
htmlacademy-vue/149336-pizza-1 pull request #1
Opened 2021-07-26 15:15 UTC by romanovaviktoriya

2021-07-26 17:51 UTC, gustoase requested changes
В целом все хорошо, пару моментов надо поправить и готово.

2021-07-26 17:51 UTC, gustoase commented on src/frontend/src/views/Index.vue
> +                <label class="dough__input dough__input--light">
Тут тоже надо сделать через v-for, данные есть в json)

2021-07-26 17:51 UTC, gustoase commented on src/frontend/src/views/Index.vue
> +                <label class="diameter__input diameter__input--small">
Тут тоже надо сделать через v-for, данные есть в json)

2021-07-26 17:51 UTC, gustoase commented on src/frontend/src/views/Index.vue
> +                  <label class="radio ingridients__input">
И тут пропустила)

2021-08-03 19:08 UTC, gustoase requested changes
Оставил комменты не там где надо, прям в коммите - https://github.com/htmlacademy-vue/149336-pizza-1/commit/49fccde078475a2359decc21545032383e37bbc5

Посмотри пожалуйста, подумай как исправить, если что пиши, помогу)

2021-08-05 11:33 UTC, romanovaviktoriya commented
> Оставил комменты не там где надо, прям в коммите - [49fccde](https://github.com/htmlacademy-vue/149336-pizza-1/commit/49fccde078475a2359decc21545032383e37bbc5)
> 
> Посмотри пожалуйста, подумай как исправить, если что пиши, помогу)

Проверь пожалуйста!

2021-08-05 11:38 UTC, gustoase approved these changes
Все хорошо получилось)

2021-08-05 12:53 UTC, merged