Разбивка компонента «Конструктор пиццы» на мелкие компоненты
htmlacademy-vue/149336-pizza-1 pull request #2
Opened 2021-08-14 19:41 UTC by romanovaviktoriya

2021-08-15 07:54 UTC, gustoase requested changes
Все в принципе неплохо, разделила на кусочки как надо, надо просто разобраться как использовать модель и обработку событий.

2021-08-15 07:54 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
Коунтер от обычного инпута ничем не отличается по сути, чтобы все правильно работало в него и как и инпут надо передать значение в модель, пропс value, его и изменять, далее эмитить событие change родителю. Почитай офф. доку https://ru.vuejs.org/v2/guide/components.html#%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-v-model-%D0%BD%D0%B0-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0%D1%85

2021-08-15 07:54 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +    counterInput: function () {
Каждый клик эмитит событие, ты не подписываешься на изменение значения.

2021-08-15 07:54 UTC, gustoase commented on src/frontend/src/common/components/RadioButton.vue
> +      this.$parent.$emit("changeRadioBtn", event.target.value, price);
Компонент ничего не знает про родителя, он только принимает модель value, изменяет ее и эмитит change обратно. Кастомные события чаще всего не нужны в простых компонентах, достаточно логики модели

2021-08-15 07:54 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +      this.$emit("changeDoughBtn", event.target.value, price);
Тут тоже юзается простая модель.

2021-08-15 07:54 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +    <div class="content__result">
BuilderPriceCounter.vue как раз содержит блок с ценой и кнопкой

2021-08-15 07:54 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +      this.$emit("changeSizeBtn", event.target.value, multiplier);
События должны описывать конкретику, например тут уместно было просто слать change. Ведь компонент ничего больше не шлет, а change нативнее.

2021-08-15 07:54 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +        <RadioButton
Скорее всего использовала parent.$emit из-за этого места. В таких случаях тут получаешь событие с радиоКнопки, и эмитишь дальше. Так намного понятнее

2021-08-15 07:54 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +            <ItemCounter :data="item" />
Получается что компонент BuilderIngredientsSelector будет агригирущим компонентом, который собирает нужные события с мини компонентов, и шлет выше данные.

2021-08-15 07:54 UTC, gustoase commented on src/frontend/src/views/Index.vue
> +      composition: {
Можно и composition применить в качестве стора. Дальше будет уже vuex который можно будет более удобно использовать в больших компонентах таких как BuilderIngredientsSelector

2021-08-15 07:56 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
После того как переделаешь на единую модель, по идее пропадет проблема "вот клики на кнопки + / - не отражается".

2021-08-15 07:56 UTC, gustoase commented on src/frontend/src/views/Index.vue
> +      composition: {
Проверять пока не обязательно ничего. Задача состоит только в том, чтобы все работало как и было, но было все разбито по маленьким компонентам.

2021-08-15 11:44 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
Что-то у мен не получается с моделью разобраться... При клике на кнопки + / - изменять props нельзя, а что делать, эмитить клик в родительский компонент и там изменять значение инпута?

2021-08-15 11:55 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
Модель\значение изменяется когда ты эмитишь событие $emit('input', ...), в документации  
![image](https://user-images.githubusercontent.com/2101423/129477664-e4a1fe08-92d3-4196-9033-54b5f12f8a24.png)

2021-08-15 11:56 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
Далее как из скрина видно, что searchInput обновиться когда изменяться данные в дочернем компоненте custom-input.

Ты просто попробуй сама создать этот компонент инпута, и поиграться, чтобы понять как оно работает. Так же там можно задать кастомное событие на изменение модели, например заменить input на change и т.п

2021-08-15 12:04 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
Родитель:
`<ItemCounter v-model="counterInput" :data="item" />`
Ребенок:
`<template>
  <div class="counter counter--orange ingridients__counter">
    <button
      type="button"
      class="counter__button counter__button--disabled counter__button--minus"
      :disabled="value <= 0"
      @click="value--"
    >
      <span class="visually-hidden">Меньше</span>
    </button>
    <input
      type="text"
      name="counter"
      class="counter__input"
      :value="value"
      @input="$emit('input', $event.target.value)"
    />
    <button
      type="button"
      class="counter__button counter__button--plus"
      :disabled="value >= 3"
      @click="value++"
    >
      <span class="visually-hidden">Больше</span>
    </button>
  </div>
</template>

<script>
export default {
  name: "ItemCounter",
  props: {
    value: {},
  },
  data() {
    return {
      counter: this.value,
    };
  },
};
</script>
`
При вводе в инпут числа, происходит замена числа во всех ингридиентах, а при кликах на + / - ничего не происходит - в компоненте value не меняется

2021-08-15 12:10 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
:data передавать не надо, у тебя в родителе про этот компонент все известно. А так

внутри @click="counterInput--"  заменяешь на @click="$emit('input', this.value - 1)". В + тоже самое. 

`data() { return { counter: this.value, }; }, };` это не нужно.

2021-08-15 12:22 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
Error in v-on handler: "TypeError: Cannot read property 'value' of null"

2021-08-15 12:38 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
Убери this в шаблоне. Вот как должно быть. У себя проверил, все идеально

<template>
  <div class="counter counter--orange ingridients__counter">
    <button
      type="button"
      class="counter__button counter__button--disabled counter__button--minus"
      :disabled="value <= 0"
      @click="$emit('input', value - 1)"
    >
      <span class="visually-hidden">Меньше</span>
    </button>
    <input
      :value="value"
      type="text"
      name="counter"
      class="counter__input"
      @input="$emit('input', $event.target.value)"
    />
    <button
      type="button"
      class="counter__button counter__button--plus"
      :disabled="value >= 3"
      @click="$emit('input', value + 1)"
    >
      <span class="visually-hidden">Больше</span>
    </button>
  </div>
</template>

<script>
export default {
  name: 'Counter',
  props: {
    value: {
      type: Number,
      required: true
    }
  }
};
</script>

2021-08-15 12:43 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
А почему во всех счетчиках меняется значение, а не в одном?

2021-08-15 12:53 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
Скорее всего во все счетчики передана одна модель. Далее надо правильно обработать модели в BuilderIngredientsSelector.vue. В цикле где обрабатываются ингредиенты, массив ingredients, надо передать как модель св-во из item, например добавить в item св-во count. Получится что-то вроде <ItemCounter v-model="item.count" /> и тогда у каждого эл-та будет своя модель

2021-08-15 12:58 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
Я так и сделала)))

2021-08-15 12:59 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
И все равно меняются все одновременно? А не только одна?

2021-08-15 18:45 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
Теперь каждый счетчик меняется отдельно. Я поняла, что затупила и поправила.

2021-08-15 19:14 UTC, romanovaviktoriya commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +            <ItemCounter :data="item" />
А как в компоненте BuilderIngredientsSelector  переслать событие из дочернего ItemCounter в родительский Index.vue
`<ItemCounter v-model="item.count"  />`
нужно указывать @input=""?

2021-08-16 06:45 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +            <ItemCounter :data="item" />
можно так, можно watch

2021-08-16 06:48 UTC, gustoase requested changes
В открытом пулл-реквесте не вижу изменений

2021-08-16 10:55 UTC, romanovaviktoriya commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +      this.$emit("changeDoughBtn", event.target.value, price);
В компоненте теста получается, что цикл внутри дочернего компонента... Передаю одну модель на все чекбоксы? Может нужно добавить еще один компонент и вынести туда label  и уже сюда передавать модель?
Родитель Index.vue:
`<div class="content__dough">`
`          <BuilderDoughSelector`
`            v-if="dough.length"`
`            :dough="dough"`
`            v-model="checkedDough"`
`          />`
`        </div>`
Ребенок BuilderDoughSelector.vue:
`<template>`
`  <div class="sheet">`
`    <h2 class="title title--small sheet__title">Выберите тесто</h2>`
`    <div class="sheet__content dough">`
`      <label`
`        v-for="item in dough"`
`        :key="item.id"`
`        class="dough__input"`
`        :class="`dough__input--${item.type}`"`
`      >`
`        <input`
`          type="radio"`
`          name="dought"`
`          :value="item.type"`
`          class="visually-hidden"`
`          :checked="item.isChecked"`
`          @change="$emit('change', $event.target.checked)"`
`        />`
`        <b>{{ item.name }}</b>`
`        <span>{{ item.description }}</span>`
`      </label>`
`    </div>`
`  </div>`
`</template>`

`<script>`
`export default {`
`  name: "BuilderDoughSelector",`
`  props: {`
`    dough: {`
`      type: Array,`
`      required: true,`
`    },`
`    checkedDough: {},`
`  },`
`};`
`</script>`

2021-08-16 11:01 UTC, romanovaviktoriya commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +    <div class="content__result">
Спасибо, упустила компонент

2021-08-16 12:08 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +      this.$emit("changeDoughBtn", event.target.value, price);
Радибатоны так и работают, есть одно имя, выбрать можно только один из немногих, следовательно в компонент передаешь список радио, и одну модель, в эту модель поместиться выбранный батон. 
Так по идее текущий компонент нормальный, не обязательно усложнять, когда переделаешь, просто глянь можно ли еще упростить

2021-08-16 18:52 UTC, romanovaviktoriya commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +      this.$emit("changeDoughBtn", event.target.value, price);
Спасибо, все получилось

2021-08-16 19:30 UTC, romanovaviktoriya commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +            <ItemCounter :data="item" />
А сам синтаксис? 
Ребенок:
`<input type="text" name="counter" class="counter__input" :value="value" @input="$emit('input', $event.target.value)" />`
Родитель:
`<ItemCounter v-model="item.count" @input="$emit('input', item.id, item.price)" />` тут довешиваю id & price
Родитель родителя:
`<BuilderIngredientsSelector  :sauces="sauces"  :ingredients="ingredients" @input="changeCounter" />`
`methods: {`
`changeCounter(newCount, id, price) {`
`...`
`},`
`},`
Правильно ли?

2021-08-17 11:00 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
Остался вопрос: как запретить ввод числа больше трех? Кнопки не позволяют нажать число больше 3, а вот клавиатура и инпут позволяют вставить... Там сейчас эмитится событие input, можно его сменить на change или v-model не будет работать?

2021-08-17 11:07 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
Чтобы сменить на другое событие, например change, это надо указать конкретно в компоненте, в [документации](https://ru.vuejs.org/v2/guide/components-custom-events.html#%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-v-model-%D1%83-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0)  про это написано.

1) А так в инпут же приходит модель с данными, эти данные ты записываешь там где-то в родителе в стор, тебе надо это провалидировать на том этапе в родителе, и не записывать в стор значение больше 3х.

Далее т.к стор не обновился и модель осталась прежней, например значение 3, тебе надо обновить темплейт компонента, применив $forceUpdate().
2) Второй вариант повозиться прям тут в компоненте, и сделать сеттер и геттер для value инпута, в котором и будет валидация

2021-08-18 11:05 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
А где можно посмотреть синтаксис применения геттера/сеттера?

2021-08-18 11:06 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
https://ru.vuejs.org/v2/guide/computed.html#%D0%A1%D0%B5%D1%82%D1%82%D0%B5%D1%80%D1%8B-%D0%B2%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D1%8F%D0%B5%D0%BC%D1%8B%D1%85-%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2

2021-08-18 11:16 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
И в ItemCounter мы передаем v-model="item.count", ума не приложу как я могу в computed задать ему сеттер и геттер...
`computed: {`
`     item.count: { /* item.count точка естественно вызывает ошибку... */`
`      set: function (newVal) {`
`         console.log("set");`
`       },`
`       get: function () {`
`         console.log("get");`
`       },`
`     },`
`  },`

2021-08-18 11:29 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
Смотри, в ItemCounter мы передаем модель, внутри ItemCounter ты и обрабатываешь еще как тебе угодно, в твоем случае модель это пришедший value.
![image](https://user-images.githubusercontent.com/2101423/129890230-157beb09-33f4-4f8f-a570-c1bf1a88362a.png)


Надо проверить этот кейс, не помню, так сработает это или нет. Если нет, попробуй this.$emit('unput', newValue)

2021-08-18 11:49 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
не сработало, буду еще пытаться.

2021-08-18 11:51 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
Закомить потом решение, хоть и не рабочее, чтобы глянуть

2021-08-19 06:45 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
Закоммитила, сделала через keydown, но почему-то посылается предыдущее значение count из ItemCounter

2021-08-19 06:51 UTC, gustoase requested changes

2021-08-19 06:51 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +      @click="$emit('input', value - 1)"
Смотри, идея состоит в том, чтобы у тебя было единое место емита события. В твоем случае уже не работает, т.к кнопками можешь увеличить хоть до 100.
Тебе надо попробовать для каждого действия вызвать одну функцию, которая будет делать инкремент\декремент, вносить данные с инпута, и там же делать валидацию, и если она проходит слать событие.

2021-08-19 06:51 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +    data: {
Отписал https://github.com/htmlacademy-vue/149336-pizza-1/pull/2#pullrequestreview-733622174

2021-08-19 07:35 UTC, gustoase requested changes

2021-08-19 07:35 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +      @keydown="validateCount($event)"
Я вижу что ты не понимаешь как это работает, лучше один раз увидеть чем сто раз страдать))
https://codesandbox.io/s/wandering-darkness-frfpt?file=/src/App.vue

2021-08-19 07:58 UTC, romanovaviktoriya reviewed
Действительно, лучше увидеть. Оказывается все гениальное - просто! ;-)

2021-08-19 07:58 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
>      validateCount(event) {
Можешь глянуть почему у меня в инпуте вводятся двойные цифры (11 вместо 1, 22 вместо 2, 33 вместо 3)?

2021-08-19 08:01 UTC, gustoase requested changes

2021-08-19 08:01 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
>      validateCount(event) {
Не понимаю где такое? Да и последнее твое решение  стоит заменить на мое, там вроде нет этой проблемы

2021-08-19 08:03 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +      @keydown="validateCount($event)"
но тут у меня вопрос был v-model у меня задается как item.count. Как я могу его в computed изменять (мне нужно чтоб имя не содержало точку)? Я туплюююю...

2021-08-19 08:06 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +      @keydown="validateCount($event)"
В itemCounter передается значение item.count, а внутри itemCounter все как и у меня остается. Просто скопипасть и посмотри как работает.

2021-08-19 08:15 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +      @keydown="validateCount($event)"
https://skr.sh/s9cU6XiK2b9

2021-08-19 08:17 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +      @keydown="validateCount($event)"
https://skr.sh/s9cU6XiK2b9 Я вот о чем.

2021-08-19 08:19 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +      @keydown="validateCount($event)"
Ну вот) https://codesandbox.io/s/wandering-darkness-frfpt?file=/src/App.vue

2021-08-19 08:22 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +      @keydown="validateCount($event)"
Обновляю item и работает

2021-08-19 08:23 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +      @keydown="validateCount($event)"
Взрыв мозга

2021-08-19 08:24 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +      @keydown="validateCount($event)"
Работает или НЕ работает при обновлении item.counter?

2021-08-19 08:30 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +      @keydown="validateCount($event)"
Работает даже так:
`watch: {`
`    item(newValue) {`
`      console.log("update model", newValue);`
`    },`
`  },`
а в консоль не выводит 
`watch: {
    item(newValue) {
      console.log("update model", newValue);
    },
  },`

2021-08-19 08:32 UTC, gustoase commented on src/frontend/src/common/components/ItemCounter.vue
> +      @keydown="validateCount($event)"
Ну т.к поле это объект с вложенной структурой, значит надо применить конфиг deep: true, почитай доку про watch vue. К тому же я показал как правильно следить за дочерними эл-тами

watch: {
    "item.counter"(newValue) {
      console.log("update model", newValue);
    },
  },

2021-08-19 08:33 UTC, romanovaviktoriya commented on src/frontend/src/common/components/ItemCounter.vue
> +      @keydown="validateCount($event)"
Благодарю!!!

2021-08-22 12:08 UTC, gustoase requested changes

2021-08-22 12:08 UTC, gustoase commented on src/frontend/src/common/components/RadioButton.vue
> +      this.$parent.$emit("changeRadioBtn", event.target.value, price);
Не исправлено

2021-08-22 12:08 UTC, gustoase commented on src/frontend/src/common/components/RadioButton.vue
> +      @change="changeRadioBtn($event, data.price)"
компонент не должен знать о тонкостях бизнес логики, как например price

2021-08-22 12:08 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +        <input
По идее у тебя уже есть RadioButton компонент, и он должен быть здесь, иначе зачем нужна была обертка

2021-08-22 12:08 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +    this.$root.$on("changeFilling", (data) => {
Не стоит размазывать логику внутри компонентом, они не должны знать о нюансах, лучше чтобы в том месте, где создается BuilderPizzaView сделать обмен данными между BuilderPizzaView и другими компонентами где требуется changeFilling

2021-08-22 12:08 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +    this.$root.$on("changeFilling", (data) => {
и в этот компонент передавать информацию, об изменении changeFilling

2021-08-22 12:08 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +          type="radio"
тут тоже надо юзать обертку

2021-08-22 12:08 UTC, gustoase commented on src/frontend/src/views/Index.vue
> +      this.$root.$emit("changeFilling", this.composition.pizzaFilling); //TODO передача между соседними компонентами
стараться не размазывать такую логику, дальше будет сложнее отлавливать зарытую логику

2021-08-22 12:11 UTC, gustoase requested changes

2021-08-22 12:11 UTC, gustoase commented on src/frontend/src/common/components/AppDrag.vue
> +  name: "AppDrag",
Когда приведешь в порядок передачу событий между компонентами, избавишься от $root.$emit() и $on, взглянешь еще раз что получилось, будет понятнее как работать с AppDrag. Там будут у тебя конкретные данные и события, сможешь манипулировать уже ими с помощью AppDrag и AppDrop

2021-08-23 19:54 UTC, romanovaviktoriya commented
Мне скорее всего нужно изменить компонент RadioButton (вынести из него label & span и оставить один input type="radio")? Иначе структура немного разнится. Я права?

2021-08-23 19:57 UTC, gustoase commented
> Мне скорее всего нужно изменить компонент RadioButton (вынести из него label & span и оставить один input type="radio")? Иначе структура немного разнится. Я права?

Лейбл должен остаться точно, остальное точно вынести

2021-08-29 11:07 UTC, romanovaviktoriya commented
Я не пропала. Сгорел блок питания ноутбука, заказала в Москве, все ещё везут… Ощущение такое, что на лошадях…

2021-09-01 19:29 UTC, romanovaviktoriya commented
Подскажи пожалуйста, как правильно задать атрибут checked?

2021-09-01 19:33 UTC, romanovaviktoriya commented
Т.е не стоит задавать атрибут?!…

2021-09-01 19:39 UTC, gustoase commented
> Т.е не стоит задавать атрибут?!…

Нет, радиокнопка содержит единственное значение на выходе и входе, и если выбранное значение в модели совпадает со значением которое передали то она считается выбранной. Единственное условие - это атрибут name по синтаксису html.

Ну вот например [изучи как сделано](https://gist.github.com/Jonarod/8553d88b1b0d1e1898ff1b5c951b00cc)

2021-09-03 11:17 UTC, romanovaviktoriya commented
Помоги с Drag'n'Drop пожалуйста

2021-09-03 11:30 UTC, gustoase commented
Эт мне надо проект твой поднять на локалке, понять че происходит прежде чем тебе помогать) Разберусь короче, отпишу.

В чем проблема у тебя конкретно?

2021-09-03 11:40 UTC, romanovaviktoriya commented
Можешь объяснить схематически, как использовать компоненты AppDrop & AppDrag, что должно куда передаваться. В курсе теории про drag'n'Drop нет, а разбор рабочего проекта не дошел.

2021-09-03 11:47 UTC, gustoase commented
Ну смотри, как я помню вроде как берется ингредиент и тащица на пиццу. Следовательно AppDrag - содержит внутри себя компонент ингредиента, AppDrop - это пицца.

AppDrag - должен содержать внутри себя информацию о ингредиент, например соус, сыр, или че там. И кол-во вроде, надо читать ТЗ как работает (подскажешь мне потом).
AppDrop - по сути просто берет то что пришло в атрибутах AppDrag и делает какую то логику, например берет соус и плюсует к нему то кол-во которое было указано в атрибуте, и для всех остальных так же.

2021-09-04 11:34 UTC, romanovaviktoriya commented
Наверно так нельзя: я указала в качестве передаваемых ингридиентов в компонент ингридиенты своего "псевдостора" (

:ingredients="ingredients" поменяла на  :ingredients="composition.ingr"). И метод moveIngridient(). Так-то оно работает как надо: при перетаскивании увеличивает счетчик ингридиента, добавляет слой изображения в конструкторе пиццы и пересчитывает итоговую стоимость. Но думаю что напахала ерунду

2021-09-05 13:10 UTC, romanovaviktoriya commented
Посмотри пожалуйста!

2021-09-06 08:37 UTC, gustoase commented
Глянул несколько коммитов, вроде похоже на правду. Получается есть мини-компоненты ингредиентов, они drag, и есть как ты указала сама пицца это drop, перенеся на нее ингредиент то увеличивается счетчик) Надо привести все в порядок и проверить что все работает как по ТЗ.

По поводу общего стора который вверху пусть будет пока так, потом будешь внедрять vuex, и сделаешь по нормальному, все оптимизируется)

2021-09-06 10:40 UTC, romanovaviktoriya commented
В ТЗ меня смущает пункты:
 - 3.2.7 Добавление в корзину 
 "При нажатии на кнопку «Готовьте» пицца с выбранными параметрами добавляется в корзину..." - нужно создать Basket.vue, перенести туда верстку корзины и делать переход по ссылке ( location.href = 'http://...), ведь роуты не изучались???
 -  3.7. Шапка сайта
 "Отображается на всех страницах сайта:

если пользователь неавторизован: отображается ссылка для входа. При нажатии осуществляется переход на страницу авторизации;
если пользователь авторизован: отображается аватар и имя пользователя. При нажатии осуществляется переход на страницу «Мои данные».
Корзина отображается для всех пользователей. Сумма формируется из стоимости всех добавленных товаров в корзину." - Тут нужно создавать страницу авторизации? Или просто по условию показывать ссылку на вход/аватар и имя юзера???

2021-09-06 12:21 UTC, gustoase commented
Ну, ты уверена что по ТЗ не пошла дальше положенного? Ведь роутинг изучается в 3ем разделе. Авторизация в 5м.

Нужно по идее сделать только корзину, и переход на нее по vue-router.

2021-09-06 12:22 UTC, gustoase commented
И судя по ТЗ ты все сделала уже 2го раздела.

2021-09-07 10:17 UTC, romanovaviktoriya commented
Еще не все, корзины нет, перехода на страницу  корзины тоже нет и отображение хедера не сделано для авторизованного/неавторизованного юзера

2021-09-13 10:15 UTC, romanovaviktoriya commented
Хотела доделать, но сделала слишком много (уже 3 модуль), испугалась, решила имеющееся сдать как 2 модуль.

2021-09-14 07:34 UTC, gustoase requested changes
В целом уже намного лучше, мелкие недочеты там и можно закрывать

2021-09-14 07:34 UTC, gustoase commented on src/frontend/src/common/components/RadioButton.vue
> +    checked: {},
Пропсы надо описывать полностью, указывая типы

2021-09-14 07:34 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +        :name="`dough`"
когда просто string, не обязательно оборачивать в кавычки

2021-09-14 07:34 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +  watch: {
Пустой вотчер

2021-09-14 07:34 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +    total: {},
типы

2021-09-14 07:34 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +  <div class="">
пустой класс

2021-09-14 07:34 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +    totalPrice: {},
тоже

2021-09-14 07:34 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +        :name="`diameter`"
стринги

2021-09-14 07:34 UTC, gustoase commented on src/frontend/src/views/Index.vue
> +            :classPizza="composition.classPizza"
:classPizza - kebab-case должен быть

2021-09-15 10:32 UTC, romanovaviktoriya commented
Скажи, могу я оставить стринги в кавычках `` и обойтись в classPizza без kebab-case?

2021-09-15 11:04 UTC, gustoase commented
> Скажи, могу я оставить стринги в кавычках `` и обойтись в classPizza без kebab-case?

Можешь, но это не соответсвует общему стилю)

2021-09-15 11:05 UTC, merged