Маршрутизатор и лейауты
htmlacademy-vue/149336-pizza-1 pull request #3
Opened 2021-09-17 11:21 UTC by romanovaviktoriya

Маршруты и лайауты есть вроде. У меня вопрос, когда нужно добиться полной работоспособности корзины (в этом задании сказано, что создать пустые страницы Cart.vue, Orders.vue, Profile.vue, Login.vue.)? А авторизация когда налаживается?

2021-09-18 16:57 UTC, gustoase commented
> Маршруты и лайауты есть вроде. У меня вопрос, когда нужно добиться полной работоспособности корзины (в этом задании сказано, что создать пустые страницы Cart.vue, Orders.vue, Profile.vue, Login.vue.)? А авторизация когда налаживается?

Так дальше еще много модулей для изучения. Там и авторизация будет, и vuex, и там будешь уже корзину реализовывать(

2021-09-18 17:04 UTC, gustoase requested changes

2021-09-18 17:04 UTC, gustoase commented on src/frontend/src/layouts/AppLayoutDefault.vue
> +    auth: {
Все булевые переменные лучше именовать с приставкой is, так понятнее)

2021-09-18 17:04 UTC, gustoase commented on src/frontend/src/views/Index.vue
> +    <router-view :auth="auth" />
Так и не понял зачем ты везде передаешь **auth** если не используешь эту переменную. Дальше когда будешь изучать vuex и авторизацию, там и сделаешь проверку на авторизацию.

2021-09-19 05:13 UTC, romanovaviktoriya commented on src/frontend/src/views/Index.vue
> +    <router-view :auth="auth" />
Я ее использую доя показа/скрытия блока юзера в хедере

2021-09-19 16:57 UTC, merged