Начало работы со стором...
htmlacademy-vue/149336-pizza-1 pull request #4
Opened 2021-09-26 11:02 UTC by romanovaviktoriya

Подключила vuex, создала файлы модулей и файл типов мутаций. И тут я подзависла... Какие мутации прописать, какие сущности вынести в стор (полностью объект composition, или удобнее по отдельности вложенные части), в конструкторе пиццы вызывать мутацию UPDATE_BUILDER или одну из множества частных случаев - UPDATE_DOUGH / UPDATE_SIZE / UPDATE_INGRIDIENTS, а если счетчик ингридиента изменяется в 0, то может вообще DELETE_ENTITY, вообще запуталась и не знаю, откуда подступить?.. Нужна помощь, волшебный пинок, немного подсказок для движения в правильном направлении? Поможешь?

2021-09-27 15:51 UTC, gustoase requested changes
У тебя должен быть стор пиццы, объект composition, далее туда переносишь в мутации то что ты делала у себя с composition. По сути ты должна сдублировать все свои действия в стор, и перестать прокидывать события в контроллер где ты обрабатывала ингредиенты, все уйдет в мутации.

По итогу там где ты например жмякаешь на соус, он апдейтит нужный соус мутацией в сторе, и запускается перерасчет цены и кол-во.

Можно универсализировать мутацию как ты и написала UPDATE_BUILDER, но логики больше будет. Попробуй так и так и увидишь что тебе будет удобнее.

А можешь например создать одну мутацию UPDATE_BUILDER которая будет общей для кастомных UPDATE_DOUGH и др, при вызове UPDATE_DOUGH вызывается внутри уже UPDATE_BUILDER который имеет универсальный код, таким образом не будет дублирование кода.

2021-09-27 15:51 UTC, gustoase commented on src/frontend/src/App.vue
> +    this.$store.dispatch("init");
Напрямую общаться со стором не желательно, лучше через mapActions

2021-09-27 15:51 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +      return this.$store.getters["Builder/PIZZA_FILLING"];
через mapGetters

2021-09-27 15:52 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +      return this.$store.getters["Builder/PIZZA_FILLING"];
А стейты через мапСтейтс

2021-09-28 11:11 UTC, romanovaviktoriya commented
В правильном ли направлении я двигаюсь? Не совсем разобралась с использованием mapGetters / mapState

2021-09-28 11:24 UTC, gustoase requested changes
В целом в правильном направлении, только все надо привести в порядок)

Так же по моей практике не обязательно использовать геттеры если они просто возвращают состояние. Лучше мапить сразу стейт.

Геттер нужен в случае если допустим он делает расчет полного имени или суммы нескольких полей.

2021-09-28 11:24 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +      return this.$store.getters["Builder/DOUGHS"];
Можно так сделать чтобы дать свое имя нужному геттеру, и убрать прямое обращение к геттеру
...mapGetters({
  DOUGHS: 'Builder/DOUGHS'
})

2021-09-28 11:24 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +      return this.$store.getters["Builder/SAUCES"];
Все это удалить, и добавить в геттер получение нужных данных. В офф доке вроде не плохо описано как это делать

https://vuex.vuejs.org/ru/guide/getters.html#%D0%B2%D1%81%D0%BF%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8F-mapgetters

2021-09-28 11:24 UTC, gustoase commented on src/frontend/src/views/Index.vue
> +      switch (this.$store.getters["Builder/COMPOSITION"].sauce.value) {
Все места заменить на описание геттеров, далее уже в условиях\шаблонах и т.п юзать алиасы указанные в геттерах, или мапстейтах.

2021-09-29 11:18 UTC, romanovaviktoriya commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +      return this.$store.getters["Builder/SAUCES"];
А как тут заменить
` ingredients() {
      return this.$store.getters["Builder/COMPOSITION"].ingr;
    },`?
    Тут вложенное свойство объекта composition нужно получить

2021-09-29 11:37 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +      return this.$store.getters["Builder/SAUCES"];
Для этого лучше сделать геттер на конкретное св-во ingr

2021-10-02 11:48 UTC, romanovaviktoriya commented
Вызов мутации изменения теста работает напрямую, но не получается добиться того же через mapActions. Получаю ошибку  "[vuex] unknown mutation type: CHANGE_DOUGH". Нагуглить стоящее не получилось. Глянь, что не так у меня, пожалуйста!

2021-10-02 11:54 UTC, gustoase commented
А ты пробовала дебажить?) Если что-то не понятно, выводишь консоль console.log(this) и посмотри что где у тебя находится по факту, есть предположение что проблема с неймпейсами у тебя. Ты указывает root, это значит что вызовется мутация из прям рута рута, а не неймспейса.

2021-10-02 12:03 UTC, romanovaviktoriya commented
Конечно пробовала, но не помогло. Действительно проблема в root: true... Спасибо!

2021-10-18 14:11 UTC, gustoase requested changes
В целом со стором намного лучше все, много мелочей, в виде оставшихся консолей и мелочей к виде UPPER case в простых переменных, ну и пустышек (это наверное чтобы не забыть на потом)

2021-10-18 14:11 UTC, gustoase commented on src/frontend/src/App.vue
> +    this.$store.dispatch("init");
осталось

2021-10-18 14:11 UTC, gustoase commented on src/frontend/src/common/helpers.js
> +import { uniqueId } from "lodash";
Когда так делаешь, ты импортишь вообще всю библиотеку, раздувая проект. Рекомендую делать так 

import uniqueId  from "lodash/uniqueId";

2021-10-18 14:11 UTC, gustoase commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +        >{{ TOTAL_PRICE_ORDER }} ₽</router-link
Вообще когда пишутся переменные с большой буквы это означает константу, у тебя же это простая динамическая переменная)

2021-10-18 14:11 UTC, gustoase commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +              :parentClass="`ingridients__counter`"
Надо следить за чистотой кода, тут например зачем доп кавычки?)

2021-10-18 14:11 UTC, gustoase commented on src/frontend/src/modules/cart/components/CartAdditionalItem.vue
> +  computed: {},
Пустышки

2021-10-18 14:11 UTC, gustoase commented on src/frontend/src/modules/cart/components/CartProductItem.vue
> +        :src="require(`@/assets/img/product.svg`)"
`@/assets/img/product.svg` а просто так не подтягивается?

2021-10-20 11:58 UTC, romanovaviktoriya commented
Проверь пожалуйста и ответь на вопросы выше

2021-10-20 18:07 UTC, gustoase commented
> Проверь пожалуйста и ответь на вопросы выше

Какие? Прошелся, ничего не вижу, можно еще раз?

2021-10-21 10:04 UTC, romanovaviktoriya commented
((
Возможно я не права, но мне удобнее UPPER_CASE в данных (в темплэйте тогда легко находишь глазами). Вот твое замечание насчет total_price_order:
"Вообще когда пишутся переменные с большой буквы это означает константу, у тебя же это простая динамическая переменная)"
Я получается заменила часть имен... **Нужно все-все?**
Еще раз вопросы:
1) "Когда так делаешь, ты импортишь вообще всю библиотеку, раздувая проект. Рекомендую делать так
import uniqueId from "lodash/uniqueId";" - у меня не получилось так импортировать, выскакивает ошибка и шаблон вообще не отображается (https://skr.sh/sAb5QNISzOk)
2)  :parentClass="`ingridients__counter`" 
У меня не получается без `` (без кавычек Vue требует такую переменную!). Покажи пример, где текст передается без кавычек пожалуйста. Или Может создать локальное свойство в секции data()?
3)

2021-10-21 10:41 UTC, gustoase commented
> (( Возможно я не права, но мне удобнее UPPER_CASE в данных (в темплэйте тогда легко находишь глазами). Вот твое замечание насчет total_price_order: "Вообще когда пишутся переменные с большой буквы это означает константу, у тебя же это простая динамическая переменная)" Я получается заменила часть имен... _Нужно все-все?_ (это тоже вопрос) Еще раз вопросы:
> 
> 1. "Когда так делаешь, ты импортишь вообще всю библиотеку, раздувая проект. Рекомендую делать так
>    import uniqueId from "lodash/uniqueId";" - у меня не получилось так импортировать, выскакивает ошибка и шаблон вообще не отображается (https://skr.sh/sAb5QNISzOk)
> 2. `:parentClass="`ingridients__counter`"`
>    У меня не получается без `` (без кавычек Vue требует такую переменную!). Покажи пример, где текст передается без кавычек пожалуйста. Или Может создать локальное свойство в секции data()?

Ну про большие переменные, это такое себе. Смотри, в твоем проекте можешь юзать, в комерческих проектах и везде все что UPPER означает константу, просто имей ввиду. И так же с нижним_подчеркиванием не надо писать простые переменные если общий стиль переменных через camelCase.

1) По скрину ты не правильно импортнула, завернула в скобочки, надо как я указал 
`import uniqueId from 'lodash/uniqueId';`

2) а в чем проблема стринг передать как стринг `parentClass="ingridients__counter"` если ingridients__counter это переменная то как обычно через двоеточие `:parentClass="ingridients__counter"`

2021-10-21 11:21 UTC, romanovaviktoriya commented
Спасибо! Все поняла. Сейчас все исправлю)

2021-10-21 11:37 UTC, romanovaviktoriya commented
а в чем проблема стринг передать как стринг parentClass="ingridients__counter" если ingridients__counter это переменная то как обычно через двоеточие :parentClass="ingridients__counter"
А у меня в компоненте ожидается пропс parentClass. Если я отправлю строку указанным способом, получается пропс не передан? Или все гуд и я не права?

2021-10-21 11:44 UTC, gustoase commented
> а в чем проблема стринг передать как стринг parentClass="ingridients__counter" если ingridients__counter это переменная то как обычно через двоеточие :parentClass="ingridients__counter" А у меня в компоненте ожидается пропс parentClass. Если я отправлю строку указанным способом, получается пропс не передан? Или все гуд и я не права?

Пропс есть пропс, он передастся в любом случае)

2021-10-24 11:24 UTC, gustoase commented
Уже лучше получается) И еще совет, давай на проверку еще и другим наставникам, чтобы было больше независимых проверок, я могу что-то упустить. Т.к итоговый зачет будет рандомный.

2021-10-24 11:24 UTC, gustoase approved these changes

2021-10-24 11:24 UTC, merged