Ошибка GET http://localhost:8080/api/users 404 (Not Found)
htmlacademy-vue/149336-pizza-1 pull request #5
Opened 2021-10-30 11:03 UTC by romanovaviktoriya

2021-10-31 10:13 UTC, Djaler commented on src/frontend/src/common/components/AppNotifications.vue
> +      :key="i"
в качестве ключа хорошо бы использовать идентификатор нотификации, а не индекс

2021-10-31 10:14 UTC, Djaler commented on src/frontend/src/common/helpers.js
> +    [resources.USERS]: new ReadOnlyApiService(resources.USERS, notifier),
так, собственно, в этом проекте нет такого маршрута. Это ты копируешь из учебного проекта

2021-10-31 10:16 UTC, Djaler commented on src/frontend/src/common/helpers.js
> +    [resources.USERS]: new ReadOnlyApiService(resources.USERS, notifier),
Сразу не сообразил почему-то.
Доступные запросы можно посмотреть в http://localhost:8080/explorer/

2021-10-31 10:34 UTC, romanovaviktoriya commented on src/frontend/src/common/helpers.js
> +    [resources.USERS]: new ReadOnlyApiService(resources.USERS, notifier),
Да, я скопипастила учебный проект, чтоб разобраться в сервисе api. Мне данные юзера в личном проекте получать запросом GET 
​api/whoAmI?

2021-10-31 10:37 UTC, Djaler commented on src/frontend/src/common/helpers.js
> +    [resources.USERS]: new ReadOnlyApiService(resources.USERS, notifier),
Да

2021-10-31 10:43 UTC, romanovaviktoriya commented on src/frontend/src/common/helpers.js
> +    [resources.USERS]: new ReadOnlyApiService(resources.USERS, notifier),
Получаю ошибку GET http://localhost:8080/api/whoAmI 401 (Unauthorized) . Видимо потому, что не авторизована

2021-10-31 10:45 UTC, Djaler commented on src/frontend/src/common/helpers.js
> +    [resources.USERS]: new ReadOnlyApiService(resources.USERS, notifier),
Всё верно. Нужно эту ошибку ловить, так мы понимаем, что не авторизованы. А авторизоваться можно по запросу /login

2021-10-31 10:46 UTC, romanovaviktoriya commented on src/frontend/src/common/helpers.js
> +    [resources.USERS]: new ReadOnlyApiService(resources.USERS, notifier),
Благодарю!

2021-11-04 17:10 UTC, Djaler commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +      <a class="header__login" @click="$router.push('/login')">
это лучше сделать с помощью router-link

2021-11-04 17:16 UTC, Djaler commented on src/frontend/src/plugins/vuePlugins.js
> +Vue.use(plugins);
этот файл нигде не импортируется, поэтому подключение плагина не происходит.
Тебе нужно в main.js его импортировать.
Либо же экспортировать из этого файла объект plugins, а сам `Vue.use` делать, опять-таки, в main.js

2021-11-19 10:56 UTC, gustoase requested changes
Не стал обращать внимание на множество комментов, думаю потом подчистишь)

2021-11-19 10:56 UTC, gustoase commented on src/frontend/src/App.vue
> +    if (this.$jwt.getToken()) {
JS асинхронен, если ты подразумевала такую логику что сначала инит, а потом уже юзер сетится то ок. А если нет, то баг)

2021-11-19 10:56 UTC, gustoase commented on src/frontend/src/common/mixins/validator.js
> +const rules = {
Если есть какая то сакральная мысль в использовании самописа то ок) А так есть отличный валидатор vee-validate

2021-11-19 10:56 UTC, gustoase commented on src/frontend/src/plugins/vuePlugins.js
> +        $jwt: () => JWTService,
По документации плагины расширяют контекст Vue, а не компонента https://ru.vuejs.org/v2/guide/plugins.html

2021-11-19 10:56 UTC, gustoase commented on src/frontend/src/services/api.service.js
> +    return address;
Точно должен возвращаться аргумент без изменения?

2021-11-19 10:56 UTC, gustoase commented on src/frontend/src/views/Login.vue
> +    this.$refs.email.$refs.input.focus();
Так нельзя делать, компонент должен тебе предоставить интерфейс работы с ним, чтобы сделать фокус. Потому что такой костыль не безопасный)

2021-11-19 10:56 UTC, gustoase commented on src/frontend/src/views/Login.vue
> +      await this.$store.dispatch("Auth/login", {
Есть mapActions

2021-11-19 11:02 UTC, gustoase commented
> 1) варианты выбора работают, но как-то кривовато,
> 2) при выборе "Новый адрес", не получается обнулить значение инпута,
> 3) плюс валидация криво отрабатывает (если одно поле пустое, то сообщение об ошибке появляется под всеми полями адреса),
> 4) как разнести правила и вотчеры валидации между файлами Cart.vue & CartForm.vue?

1)  что именно?
2,3,4) советую убрать кастом валидацию и заюзать готовую vee-validate

2021-11-19 11:02 UTC, gustoase commented on src/frontend/src/modules/cart/components/CartForm.vue
> +            :value="street"
Зачем value и v-model одновременно? По идее в переменной которую передаешь в v-model подсовываешь дефолтное значение street и оно отобразится в компоненте

2021-11-20 08:24 UTC, romanovaviktoriya commented on src/frontend/src/views/Login.vue
> +    this.$refs.email.$refs.input.focus();
Что имеется ввиду под "компонент должен тебе предоставить интерфейс работы с ним"? Как правильно поставить фокус на первом поле?

2021-11-20 08:26 UTC, romanovaviktoriya commented on src/frontend/src/common/mixins/validator.js
> +const rules = {
А можно использовать vee-validate? По ТЗ?

2021-11-20 10:31 UTC, romanovaviktoriya commented on src/frontend/src/common/mixins/validator.js
> +const rules = {
фокус не удался, https://skr.sh/sB737IYqcXp, не нахожу папку vee-validate в node_modules/

2021-11-21 07:35 UTC, romanovaviktoriya commented on src/frontend/src/modules/cart/components/CartForm.vue
> +            :value="street"
:value удалила, оставила v-model

2021-11-21 07:36 UTC, romanovaviktoriya commented
Подключила vee-validate, но проблема с обнулением полей при выборе селекта "Новый адрес" осталась

2021-11-21 07:36 UTC, romanovaviktoriya commented on src/frontend/src/views/Login.vue
> +      await this.$store.dispatch("Auth/login", {
+

2021-11-21 07:37 UTC, romanovaviktoriya commented on src/frontend/src/common/mixins/validator.js
> +const rules = {
Все получилось

2021-11-21 12:46 UTC, gustoase commented on src/frontend/src/views/Login.vue
> +    this.$refs.email.$refs.input.focus();
Ну смотри, у тебя есть компонент к которому ты обращаешься через ref **this.$refs.email** когда так делаешь, тебе в email доступны все описанные методы, данные и т.п.

Ты можешь сделать метод в компоненте который вызовешь, типа this.$refs.email.addFocus()  this.$refs.email.removeFocus()

2021-11-21 12:46 UTC, gustoase commented on src/frontend/src/views/Login.vue
> +    this.$refs.email.$refs.input.focus();
Интерфейс это не кнопочки, это то через что ты работаешь на программном уровне)

2021-11-21 13:42 UTC, gustoase commented
> Подключила vee-validate, но проблема с обнулением полей при выборе селекта "Новый адрес" осталась

По хорошему тебе разобраться с этой проблемой, погуглить почему в селектах не пропадает ошибка. НО ты можешь руками убрать ошибку раз на то пошло, временно конечно же

2021-11-22 19:52 UTC, romanovaviktoriya commented
Можешь еще глянуть, насколько верно я сделала взаимодействие ProfileAddressView.vue -> Profile.vue -> ProfileAddressEdit.vue через props/emit (не заходила плодить еще поля под изменяемый адрес в сторе). Или стоило обойтись без пропсов и воспользоваться стором??? Получилось мудрено и я не разберусь, почему AppInput.vue матерится на входные параметры при Добавлении нового адреса?

2021-11-22 19:56 UTC, romanovaviktoriya commented
vee-validate требует v-model на поле input, а компонент ожидает :value. Может изменить AppInput как-то?

2022-01-02 20:57 UTC, Djaler commented on src/frontend/src/layouts/AppLayoutUser.vue
> +    <AppLayoutHeader />
в этом лейауте тоже по идее нужно добавить AppNotifications. либо в AppLayout добавить, чтоб везде был

2022-01-02 21:02 UTC, Djaler commented
Не работает изменение пиццы из корзины - просто добавляется новая пицца, а не меняется существующая.

2022-01-02 21:02 UTC, Djaler commented
Не пересчитывается цена пиццы при добавлении ингредиента перетаскиванием

2022-01-02 21:09 UTC, Djaler commented
> почему AppInput.vue матерится на входные параметры при Добавлении нового адреса?

Потому ты берешь у пропса adr свойства id, name и т.д. а у него таких нет (там addrId, addrName и т.д.) Поэтому получается undefined в значении, а у AppInput проп value указан как required

2022-01-02 21:11 UTC, Djaler commented
>Можешь еще глянуть, насколько верно я сделала взаимодействие ProfileAddressView.vue -> Profile.vue -> ProfileAddressEdit.vue через props/emit (не заходила плодить еще поля под изменяемый адрес в сторе). Или стоило обойтись без пропсов и воспользоваться стором???

В целом нормально, разве что я бы не делал отдельное поле visibleForm, а завязался исключительно на состояние editableAddress. Его можно делать null, что будет означать необходимость скрыть эту форму

2022-01-02 21:20 UTC, Djaler commented on src/frontend/src/common/components/AppNotifications.vue
> +      :key="i"
не исправлено

2022-01-02 21:24 UTC, Djaler commented on src/frontend/src/modules/orders/components/OrdersItem.vue
> +    repeatPizzaMethod(order) {
тут order и так доступен по this.order, поэтому можно не передавать его в параметрах

2022-01-02 21:26 UTC, Djaler commented on src/frontend/src/store/modules/builder.store.js
> +        value: "light",
этих данных теоретически может не быть в полученных из апи данных, поэтому нехорошо тут на них завязываться. По хорошему устанавливать дефолтное состояние при получении списка данных (брать первое значение теста, размера и т.д.)

2022-01-02 21:27 UTC, Djaler commented on src/frontend/src/store/modules/builder.store.js
>            price = item.price;
тут надо либо использовать forEach (так, как сейчас используется filter), либо find (чтобы найти нужный item и из него уже достать price и id). Сам filter не должен делать никаких сайд эффектов

2022-01-03 10:52 UTC, romanovaviktoriya commented on src/frontend/src/layouts/AppLayoutUser.vue
> +    <AppLayoutHeader />
Спасибо, поправила

2022-01-03 11:28 UTC, romanovaviktoriya commented on src/frontend/src/modules/orders/components/OrdersItem.vue
> +    repeatPizzaMethod(order) {
Точно, поправила!

2022-01-03 11:37 UTC, romanovaviktoriya commented on src/frontend/src/store/modules/builder.store.js
> +        value: "light",
Ммм... А как при заполнении стора мне обратиться к апи и указать первое значение из полученных? Или заполнить стор прям из экшена (например тесто заполнить внутри async queryDough?

2022-01-03 11:43 UTC, Djaler commented on src/frontend/src/store/modules/builder.store.js
> +        value: "light",
Да, я такой вариант имел в виду. Главное учесть это, чтоб компоненты билдера адекватно реагировал на временное отсутствие значений

2022-01-03 11:45 UTC, romanovaviktoriya commented on src/frontend/src/store/modules/builder.store.js
> +        value: "light",
Получилось!

2022-01-04 07:47 UTC, romanovaviktoriya commented on src/frontend/src/store/modules/builder.store.js
>            price = item.price;
Спасибо, поняла, исправила.

2022-01-04 11:22 UTC, Djaler commented
Ещё небольшой момент - думаю, в AppDrop стоит обернуть только BuilderPizzaView. Потому что сейчас получается, что не важно куда тянешь ингредиент - он добавится, нет возможности отменить это

2022-01-04 11:22 UTC, merged