Module6 task1
htmlacademy-vue/149336-pizza-1 pull request #6
Opened 2022-01-06 11:24 UTC by romanovaviktoriya

Для меня загадка, почему необходимо оборачивать router-view в transition
`<transition name="slide" mode="out-in">
        <router-view />
 </transition>`
 , а потом еще и в каждом лайауте это делать:
 `<transition name="slide" mode="out-in">
      <slot />
  </transition>`?
  Иначе не работает.
  Из-за наличия transition вокруг router-view очень не красиво отрабатывает открытие роута login (в затемнении что-то выезжает, в потом резко появляется попап).
  Плюс не пойму почему не работает transition в попапе "Спасибо за заказ"?

2022-01-06 18:26 UTC, Djaler requested changes

2022-01-06 18:26 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
>                `pizza__filling--${item.name}`,
не совсем корректно отображается пицца при добавлении нескольких одинаковых ингредиентов. судя по всему, нужно, если ингредиента 2 - чтоб было 2 div
pizza__filling pizza__filling--name
pizza__filling pizza__filling--name pizza__filling--second

Ну и когда 3 - аналогично. Тогда будет явно видно, что добавлено несколько единиц ингредиента.
И надо в этом месте про анимацию тоже не забыть, чтобы корректно она срабатывала при добавлении второго и третьего ингредиента (нужно правильно key задать)

2022-01-06 18:26 UTC, Djaler commented on src/frontend/src/App.vue
>      <AppLayout>
судя по всему, проблема вот из-за чего:
когда мы переходим по маршрутам, у нас внутри AppLayout сменяется компонент, рисующий текущий лейаут. Соответственно, заново содержимое слота рендерится заново, а не заменяется. Поэтому и не срабатывает transition.
Самое простое решение - добавить проп appear на transition тут. Тогда анимация будет срабатывать при изначальном рендеринге содержимого (которое, по сути, будет происходить при каждом переходе на страницу с другим layout)

2022-01-06 18:26 UTC, Djaler commented on src/frontend/src/views/Popup.vue
> +  <transition name="slide-fade">
а с попапом - мне кажется, проблема тоже кроется в layout. когда отображается этот маршрут, меняется лейаут вокруг основного router-view. как-то мне это не нравится. я бы оставил для этого маршрута тот же лейаут, что и у родительского, а подложку с затемненением перенес в сам компонент Popup. попробуй так

2022-01-06 18:26 UTC, Djaler commented on src/frontend/src/layouts/AppLayoutDefault.vue
>    <div class="app-layout-default">
ну и в целом этот лейаут какой-то слишком специфичный, для того чтобы называться default. в default я бы просто рисовал slot и всё

2022-01-06 19:10 UTC, romanovaviktoriya commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
>                `pizza__filling--${item.name}`,
Хм.. Но в ТЗ указано что добавляется <div class="pizza__filling pizza__filling--name"></div>, а потом добавляется только класс second/third.

2022-01-06 19:34 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
>                `pizza__filling--${item.name}`,
по-моему, в какой-то момент меняли стили для этого дела, возможно у тебя остались старые стили, поэтому нужно именно 1/2/3 div делать

2022-01-07 08:06 UTC, romanovaviktoriya commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
>                `pizza__filling--${item.name}`,
Стили действительно старые, так как нет псевдоэлементов before & after для pizza__filling (в этом случае див один, а классы вешаются в зависимости от количества 1/2/3). Если стили оставить как есть и вставлять по 1/2/3 дива, то получается вот так анимировать https://skr.sh/vBtkz5R3AMI?a (хотя при итоговой проверке могут прицепиться, что реализация не соответствует ТЗ, где черным по белому написано 
`Если добавляется 2 одинаковых ингредиента, то в div.pizza__wrapper нужно добавить код:
<div class="pizza__wrapper">
    <div class="pizza__filling pizza__filling--ananas pizza__filling--second"></div>
</div>
Если добавляется 3 одинаковых ингредиента, то код будет:
<div class="pizza__wrapper">
    <div class="pizza__filling pizza__filling--ananas pizza__filling--third"></div>
</div>`

2022-01-07 08:09 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
>                `pizza__filling--${item.name}`,
Это не принципиально, я думаю. Тут главное - как оно работает в итоге

2022-01-07 10:36 UTC, romanovaviktoriya commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
>                `pizza__filling--${item.name}`,
Тогда одной проблемой меньше

2022-01-07 10:44 UTC, romanovaviktoriya commented on src/frontend/src/App.vue
>      <AppLayout>
appear помогло!

2022-01-07 13:33 UTC, romanovaviktoriya commented on src/frontend/src/views/Popup.vue
> +  <transition name="slide-fade">
Попапы "Спасибо" и "Логин" выглядят ужасно https://skr.sh/vBtEw86MH3B при проигрываемой transition  в AppLayout. Может наоборот перенести transition внутрь AppLayoutMain.vue, а в лайаутах попапов не прописывать transition и добавить его в Login.vue & Popup.vue?

2022-01-07 13:38 UTC, Djaler commented on src/frontend/src/views/Popup.vue
> +  <transition name="slide-fade">
Да, можно попробовать так. Ещё, вероятно, может быть конфликт стилей - выравнивание попапов по центру реализовано с помощью transform: translate. И у тебя тут в анимации, насколько я вижу, transform используется. Можно попробовать выравнивание по центру другим способом сделать, например, с помощью `margin: auto`

2022-01-07 14:55 UTC, romanovaviktoriya commented
Вроде неплохо получилось. Установила animate.css с помощью npm, но не смогла импортировать файл animate.css в стили компонента или в main.js. Ошибка Not found module... Пришлось подключить в index.html с помошью <link>. Работает, но хотелось бы избавиться от CDN и оставить npm-пакет. ПОдскажешь, как правильно импортнуть файл animate.css, чтоб заработало?

2022-01-07 14:55 UTC, romanovaviktoriya commented on src/frontend/src/views/Popup.vue
> +  <transition name="slide-fade">
Посмотри пожалуйста, что получилось

2022-01-07 14:57 UTC, romanovaviktoriya commented
Блин, нужно же было анимацию slide...(((

2022-01-07 15:00 UTC, romanovaviktoriya commented
Почему не отрабатывает вторая анимация? 
`<transition
      mode="out-in"
      appear
      name="profile"
      enter-active-class="animate__animated animate__fadeInDown"
      leave-active-class="animate__animated animate__fadeOutDown"
    >`

2022-01-07 15:12 UTC, Djaler commented
> ПОдскажешь, как правильно импортнуть файл animate.css, чтоб заработало?

Просто в main.js импортируется. Может быть перезапустить дев-сервер после установки пакета?

2022-01-07 15:39 UTC, Djaler commented
> Почему не отрабатывает вторая анимация?

Судя по всему, проблема всё та же - компонент лейаута перерендеривается при каждом переходе по маршруту, поэтому нет момента, когда может сработать `leave-active-class`. При чём перерендеривается он даже если лейаут указан одинаковый. Пока не понял как это обойти

2022-01-07 15:40 UTC, Djaler commented
![image](https://user-images.githubusercontent.com/7964583/148567897-260453f5-0a1d-4038-9b1d-8fb7c43e52c9.png)
Вот так сделал - видно, что computed и дёргается watch каждый раз

2022-01-07 15:52 UTC, Djaler commented
Можно, конечно, поместить transition вокруг самого `<component :is`, но тогда анимироваться будет и хедер, и сайдбар

2022-01-08 10:39 UTC, romanovaviktoriya commented
Блин, что же делать...

2022-01-08 16:42 UTC, Djaler commented
Появилась у меня гениальная идея.
Почему тут происходит перерендеринг компонента, даже при том, что лейаут не поменялся? потому что каждый раз, когда вызывается computed layout, результат `() => import(`@/layouts/${layout}.vue`)` - это новый объект. Нам нужно добиться того, чтобы такого не происходило. Вот как это можно сделать:
1. Выносим импорт компонента в мета-информацию маршрутов, вместо имени лейаута
2. В AppLayout просто используем этот компонент (либо дефолтный)
![image](https://user-images.githubusercontent.com/7964583/148652310-e8b9fc03-db6c-4de2-82c2-70b365cb1d2c.png)
![image](https://user-images.githubusercontent.com/7964583/148652321-6cb35984-0e0e-4e4c-b853-8a2871a6c49d.png)
И теперь, если лейаут не меняется, то компонент не перерендеривается.
P.S. Подстановку дефолтного лейаута я не сделал тут, это надо докрутить

2022-01-08 20:00 UTC, romanovaviktoriya commented
Поправила, как написал. https://skr.sh/sBuH99tcrQu , https://skr.sh/sBuHnJXLWW7 , но кажется ничего не изменилось https://skr.sh/vBupbdUl2hP

Еще я днем мучала вариант с JS-хуками, получила что-то похожее на то, что нужно, но не без костылей.
https://skr.sh/sBuhyS102dG
https://skr.sh/sBulLd1M2im
https://skr.sh/sBuuE5UgocY
 Плюс после скрытия попапа, он почему-то мелькает вновь https://skr.sh/vBuF2Sw14to?a

2022-01-08 20:03 UTC, Djaler commented
> но кажется ничего не изменилось https://skr.sh/vBupbdUl2hP

Это потому что при переходе на /login всё-таки меняется layout. А если попробовать переход / -> /cart?

2022-01-08 20:05 UTC, romanovaviktoriya commented
Между главной и корзиной все супер.

2022-01-08 20:07 UTC, Djaler commented
Ну а вот чтобы сохранялась анимация при переходе между разными лейаутами - даже не знаю, что сделать. Есть ощущение, что  все на этот момент просто забивали) Либо transition делали поверх лейаута, а не в нём. Можно спросить в слаке, что народ думает по этому поводу

2022-01-08 20:10 UTC, romanovaviktoriya commented
Так и сделаю. Просто странно, что в модуле 6 так мало вопросов, видимо у всех остальных все легко получилось с анимацией или действительно забивали и не парились

2022-01-09 19:39 UTC, romanovaviktoriya commented
Никто не отвечает в slack, а сроки поджимают (у меня до 26 янв доступно обучение), может так пойдет? Костыльно, не правильно, но

2022-01-10 06:08 UTC, Djaler commented on src/frontend/src/modules/orders/components/OrdersItem.vue
> +        this.order.orderPizzas !== "underfined" &&
тут наверное `underfined` без кавычек должно быть

2022-01-10 06:09 UTC, Djaler commented
Пойдет

2022-01-10 06:09 UTC, merged