Module7 task1
htmlacademy-vue/149336-pizza-1 pull request #7
Opened 2022-01-20 11:57 UTC by romanovaviktoriya

Никак не разберусь с ошибками в тесте ItemCounter.spec.js. Как правильно протестировать клик по кнопке +/-, как проверить навешивание/удаление атрибута disabled?

2022-01-20 19:06 UTC, Djaler commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    await btnPlus.trigger('click');
Тут всё правильно

2022-01-20 19:09 UTC, Djaler commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
а тут у нас действительно атрибут disabled не появляется, потому что, когда мы в компоненте меняем значение (вводом в инпут или нажатие на кнопку), мы только кидаем событие наверх, и всё. При реальном использовании сверху это событие кто-то обрабатывает и нам в проп value поступает обновленное значение. Но в тесте этого не происходит. Собственно, то, что наверх кидаются события, мы протестировали уже. А чтобы протестировать установку disabled нужно не имитировать какое-то пользовательское действие, а установить подходящее значение пропа value

2022-01-20 19:09 UTC, Djaler commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    wrapper.vm.$nextTick(() => {
ну и просто на будущее, $nectTick можно дёргать вот в таком виде - `await wrapper.vm.$nextTick()`

2022-01-21 11:59 UTC, romanovaviktoriya commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
так у меня нет prop disabled. У меня в зависимости от пропс value, вычисляется computed-свойство internalValue и если оно выходит за рамки 0-3, то устанавливается :disabled="internalValue <= 0" или :disabled="internalValue >= 3"

2022-01-21 12:00 UTC, Djaler commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
Вот тебе в тесте и нужно этот проп `value` установить такой

2022-01-21 12:04 UTC, romanovaviktoriya commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
устанавливаю 3, но тест с ошибкой падает... https://skr.sh/sC7MAaxI68o

2022-01-21 12:06 UTC, Djaler commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
Коллбек внутрь $nextTick не нужно передавать.
Просто проверку нужную делай уже после await

2022-01-21 12:07 UTC, Djaler commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
Ну и я вижу, что ты всё ещё устанавливаешь значение инпута и делаешь trigger input на нём. Это не нужно

2022-01-21 14:20 UTC, romanovaviktoriya commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
Никак не получается. https://skr.sh/sC7GidPibjL

2022-01-21 14:21 UTC, romanovaviktoriya commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
Пропс вот https://skr.sh/sC76Kj2NSJh

2022-01-21 14:31 UTC, romanovaviktoriya commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
А атрибут disable не устанавился... https://skr.sh/sC7F1NkokNw Почему? как правильно установить значение пропс?

2022-01-22 07:10 UTC, Djaler commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
```
it('Check that the disabled attribute is added to the buttons', async () => {
    createComponent({ propsData });
    await wrapper.setProps({value:3})
    let btn = wrapper.find('.counter__button--plus');
    await wrapper.vm.$nextTick();
    expect(btn.attributes('disabled')).toBe('disabled');
  });
  ```

2022-01-22 07:11 UTC, Djaler commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
Ну либо менять исходный propsData, типа 
```
it('Check that the disabled attribute is added to the buttons', async () => {
    createComponent({
      propsData: {
        ...propsData,
        value: 3
      }
    });
    let btn = wrapper.find('.counter__button--plus');
    await wrapper.vm.$nextTick();
    expect(btn.attributes('disabled')).toBe('disabled');
  });
  ```

2022-01-22 07:12 UTC, Djaler commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
Свойство props во втором аргументе shallowMount передавать не надо, это ты так переопределяешь определенные в компоненте пропсы. А чтоб передавать именно их значения - нужен propsData

2022-01-22 10:42 UTC, romanovaviktoriya commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
Спасибо ОГРОМНОЕ! Заработало

2022-01-22 11:38 UTC, romanovaviktoriya commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
Как быть с checked? https://skr.sh/sC8QqBD1tBz Я так понимаю, что зря я использовала не boolean тип пропса checked... Можно как-то в тесте передать checked = '1'?

2022-01-25 11:14 UTC, romanovaviktoriya commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
Руководствуясь https://lmiller1990.github.io/vue-testing-handbook/ru/computed-properties.html#%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BE%D1%82%D1%80%D0%B8%D1%81%D0%BE%D0%B2%D0%BA%D0%B8-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B9 сделала так https://skr.sh/sCBjwXXDpU0 можно ли так тестировать и не вызовет ли проблем с защитой проекта такой тест (без задействования mount / shallowMount?

2022-01-25 12:30 UTC, Djaler commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
"Тестирование через call" - очень плохая практика. Так мы не проверяем реальное поведение компонента.

В твоём случае проверять нужно примерно вот так:
```
it('Check that the checked attribute is added to the radio buttons', async () => {
    createComponent({ propsData });
    let input = wrapper.find('input[type="radio"]');
    await wrapper.setProps({checked: 'type1', value: 'type1'})
    expect(input.element.checked).toBe(true);
    await wrapper.setProps({checked: 'type2'})
    expect(input.element.checked).toBe(false);
  });
  ```
  `.attributes('checked')` здесь, видимо, не подходит, потому что checked это какой-то не простой атрибут, его видимо нужно напрямую на элементе смотреть

2022-01-25 12:30 UTC, Djaler commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
Могу посоветовать хорошее видео на эту тему (что и как правильно тестировать во вью) https://www.youtube.com/watch?v=L_BK8zXGdBM

2022-01-25 12:58 UTC, romanovaviktoriya commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    // expect(btn.attributes('disabled')).toBe('disabled');
Спасибо!

2022-01-25 14:01 UTC, Djaler commented
Чтобы протестировать totalPrice, нам нужно просто вызвать эту функцию, передав туда объект ожидаемой структуры. То есть, не обязательно создавать какой-то тестовый стор. Мы просто можем создать объект store, типа
```
const store = {
  Builder: {
    ingredients: [...],
    ...
  }
}
```

Разве что, мне не очень нравится, что эта функция не чистая - она и возвращает результат, и меняет данные в переданном ей order. Может быть заодно тут отрефакторить этот момент чуть-чуть

2022-01-25 15:52 UTC, Djaler commented
А насчёт консультации - может быть у неё тип сменить на текстовую или кодревью. А то так непонятно, какое время вносить)

2022-01-25 16:57 UTC, romanovaviktoriya commented
Я бы так и сделала, но почему-то иные виды консультаций стали мне недоступны...

2022-01-25 17:04 UTC, Djaler commented
Может потому что предыдущее код ревью ещё не было закрыто? А если сейчас попробовать отменить и заново завести

2022-01-26 06:59 UTC, romanovaviktoriya commented
Сорри, вчера не было времени, а сегодня по идее я уже ничего не смогу изменить. Полгода закончилось, теперь заново оплачивать и тогда продолжать.

2022-02-03 17:58 UTC, Djaler commented on src/frontend/src/views/__tests__/Index.spec.js
> +  + @drop="moveIngridient($event)"
находим дочерний компонент по какому-либо селектору. Например, `const ingredientsSelector = wrapper.findComponent(BuilderIngredientsSelector)`. А потом эмулируем на нём бросание события - `ingredientsSelector .vm.$emit('drop', {id: ..., count: ... })`

2022-02-03 18:03 UTC, Djaler commented on src/frontend/src/views/__tests__/Login.spec.js
> +import { mount, createLocalVue } from '@vue/test-utils';
По умолчанию jest не применяет никакие трансформации к коду в node_modules. Но иногда это нужно, когда библиотеки используют синтаксис, который jest сам по себе не понимает (нужен бабель). Для этого нужно поменять настройку transformIgnorePatterns в jest.config.js.
Тебе нужно что-то такое: `transformIgnorePatterns: ["/node_modules/(?!(vee-validate)/)"],`. Так мы исключаем из трансформации всё в node_modules, кроме этого конкретного пакета, его мы трансформируем

2022-02-04 11:07 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Index.spec.js
> +  + @drop="moveIngridient($event)"
Я думала геттер - если относится к одному модулю, а тут минимум к двум (cart & builder)?

2022-02-04 11:09 UTC, Djaler commented on src/frontend/src/views/__tests__/Index.spec.js
> +  + @drop="moveIngridient($event)"
Почему? Цена текущей пиццы рассчитывается только по данным из билдера

2022-02-04 11:09 UTC, Djaler commented on src/frontend/src/views/__tests__/Index.spec.js
> +  + @drop="moveIngridient($event)"
Но вообще теоретически геттер может брать данные из другого модуля

2022-02-04 11:43 UTC, romanovaviktoriya commented
У меня не проходит тест на клик по router-link (не button) https://skr.sh/sCLNh4XavBR Как тут быть?

2022-02-04 11:44 UTC, Djaler commented
Так а что за вызов dispatch ты там ожидаешь?

2022-02-04 11:46 UTC, Djaler commented
Ну и если это router-link, то rouer.push вызываться тоже не будет. Клик по ссылке я бы вообще в этом случае не тестировал. Имеет смысл тестировать формирование самой ссылки, если оно динамическое. Например, если у тебя есть список пользователей, и у каждого есть ссылка на его личную страницу, в итоге to для ссылки формируется как `{ name: 'User', params: { userId: 2 }}`. В таком случае можно взять у этого router-link проп to и посмотреть, что там ожидаемый результат. А так как тут статически забито - не стоит

2022-02-09 11:25 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Index.spec.js
> +  + @drop="moveIngridient($event)"
Создала я геттер
`getTotalPrice: (state) => {
      let multi;
      let newArr = [];
      state.composition.pizzaFilling.forEach((element) => {
        newArr.push(element.count * element.price);
      });
      if (newArr.length !== 0) {
        multi = newArr.reduce((sum, current) => sum + current, 0);
      } else {
        multi = 0;
      }
      // (Основа + Соус + Добавки) * размер
      let newTotalPrice =
        (state.composition.dough.price +
          state.composition.sauce.price +
          multi) *
        state.composition.size.multiplier;
      state.composition.totalPrice = newTotalPrice;
      return state.composition.totalPrice;
    },`
Все работает хорошо до момента заказа. Неавторизованный юзер делает заказ->Спасибо->Переход на главную, а в сторе 
https://skr.sh/sCQHjUMo1n0
Внутри composition totalPrice обнуляю в мутации RESET_BUILDER
`... state.composition.totalPrice = 700;`
Как быть? Может лучше оставить хелпером, как было?

2022-02-10 06:17 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Index.spec.js
> +  + @drop="moveIngridient($event)"
После пересборки все вроде норм

2022-02-11 21:32 UTC, Djaler commented on src/frontend/src/store/modules/builder.store.js
> +      state.composition.totalPrice = newTotalPrice;
не нужно тут ничего сохранять в стейт. Геттер - это то же самое, что и computed в компоненте, у него не должно быть никак побочных эффектов. Он только возвращает значение и всё. То есть, из стейта тебе это поле нужно убрать вообще

2022-02-11 21:34 UTC, Djaler commented on src/frontend/src/store/modules/builder.store.js
> +      state.composition.totalPrice = newTotalPrice;
Ну и соответственно, тогда в CREATE_PIZZA/EDIT_PIZZA тебе нужно будет получать данные о цене уже из геттера, а не из стейта. И к слову, сильно мне не нравится, что там в мутацию передаётся rootState целиком. Лучше всё-таки на уровне экшена извлечь то что нужно и передать в мутацию только необходимые куски данных

2022-02-11 21:37 UTC, Djaler commented
А насчёт ошибки - вряд ли тут геттер замешан, скорее всего это было сломано и раньше. Смотри, вот в каком виде у нас хранятся заказы, полученные с бекенда:
![image](https://user-images.githubusercontent.com/7964583/153673516-478f1378-7062-4b2c-8e2a-b9b6b81d6264.png).
Но ты в экшне newOrder (orders.store) добавляешь в список `orders` данные, полученные из результата запроса на добавление заказа. А там данные совсем не такие - 
![image](https://user-images.githubusercontent.com/7964583/153673620-175f47f1-3a22-40bd-8c35-c94ad3101885.png)
Поэтому сначала, когда открывается страница заказов, там пытается отобразиться вот такой неправильный ордер, получается ошибка. А потом загружаются нормальные данные и всё отображается

2022-02-11 21:40 UTC, Djaler commented
Ещё из того, что я сейчас заметил:
1. В BuilderPriceCounter в createPizzaMethod ты дёргаешь загрузку информации об адресах. Во-первых, это нужно только для авторизированного пользователя. Во-вторых, это не должно быть в этом месте. Получается, этот компонент знает, что потом на странице корзины нам понадобятся эти данные. Вызов этого запроса должен быть уже в одном из компонентов корзины.
2. В самой корзине - для неавторизированного пользователя должен быть доступен ввод адреса, а не только самовывоз
3. Геттеры вот такого вида особой пользы не несут, вполне можно обращаться к стейту напрямую. Геттеры нужны, если есть какое-то преобразование данных
![image](https://user-images.githubusercontent.com/7964583/153674043-edcd3b85-c9bd-4133-9af3-e45813d6437f.png)

2022-03-09 21:40 UTC, Djaler commented on src/frontend/src/common/helpers.js
>      let newIngrs = [];
этот хелпер делает очень много вещей сразу, я сходу не могу разобраться что именно. Но это точно не соответствует названию

2022-03-09 21:44 UTC, Djaler commented on src/frontend/src/views/Cart.vue
>      },
тут в `totalPriceOrder` не должно быть вызова экшена. получается, что ты и тут считаешь итоговую стоимость заказа, и отдельно вызывает расчёт того же самого в сторе.
в самом сторе это не должно быть экшеном и мутацией - это опять-таки, должен быть геттер. доступа к rootData тебе там не нужно (хотя геттер может обращаться к другим модулям), потому что все нужные данные уже лежат в этом модуле.
а в компоненте ты просто этот посчитанный геттер будешь использовать для вывода. и его же - в хедере

2022-03-09 21:50 UTC, Djaler commented
Насчёт повтора заказа - ты и правда можешь вынести расчёт цены пиццы в какую-то вспомогательную функцию, которую будешь дёргать в том числе и в геттере getTotalPrice. Функция сама по себе в стор не должна ходить, она должна просто принимать в качестве параметра твой объект composition.
Тогда при повторе заказа ты сможешь для каждой добавляемой в заказ пиццы расчитывать её цену, используя этот хелпер, аналогично тому, как сейчас ты добавляешь пиццу в корзину, используя геттер 
![image](https://user-images.githubusercontent.com/7964583/157542179-54fa3beb-97e6-4787-968b-7c597bf7f3b4.png)

2022-03-10 20:16 UTC, romanovaviktoriya commented on src/frontend/src/views/Cart.vue
>      },
С этим разобралась, написала геттер getTotalPriceOrder, удалила экшен updateTotalPriceOrder, мутацию UPDATE_TOTAL_PRICE_ORDER и метод changePriceOrderMethod().

2022-05-02 18:14 UTC, Djaler requested changes

2022-05-02 18:14 UTC, Djaler commented on src/frontend/src/views/__tests__/Cart.spec.js
> +  // );
Так как бы дёргаем commit у самого store, он не знает о том, в каком модуле искать мутацию с таким названием. Поэтому нужно сделать вот так:
```
store.commit(
    "Cart/" + CREATE_PIZZA,
    {
      composition: pizza.composition,
      getTotalPrice: pizza.price,
    }
  );
  ```
  То есть, вместе с именем мутации указываем и название модуля. Ну а опция root нам тут вообще не нужна, так как мы и так вызываем мутацию в корне, а не из контекста какого-то модуля

2022-05-02 18:14 UTC, Djaler commented on src/frontend/src/views/__tests__/Cart.spec.js
> +  store.state.Cart.phone = "+7 999-999-99-99";
так как ты используешь в этих тестах mount, а не shallowMount, то логично симитировать настоящий ввод этого значения, а не устанавливать его напрямую в сторе (так как значение устанавливается на этой странице).
Разумеется, делать тогда это нужно уже после монтирования компонента.
Находим инпут по селектору `'[name="tel"]'` (или добавляем какой-то вспомогательный data-test атррибут), делаем на нём await input.setValue('+7 999-999-99-99')

2022-05-02 18:14 UTC, Djaler commented on src/frontend/src/views/__tests__/Cart.spec.js
> +  store.state.Cart.phone = "+7 999-999-99-99";
Ввод адреса - аналогично, нужно делать имитацию ввода в инпуты

2022-05-02 18:14 UTC, Djaler commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Auth.newAddresses).toHaveBeenCalled();
а насчёт самой проверки - в целом, да, в таких случаях проверяем через toHaveBeenCalledWith, передавая ожидаемый объект. 
Но вообще тут по самому коду не совсем правильно - не нужно дёргать запрос на добавление адреса вручную. Это автоматически происходит на бекенде, когда мы шлём в заказе новый адрес.
Так что тебе это нужно вообще убрать. Но потом все равно аналогичным образом проверять корректность вызова экшена newOrder, конечно

2022-05-03 10:51 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Auth.newAddresses).toHaveBeenCalled();
А что тогда вообще нужно тестировать из списка внизу страницы?

`// Список элементов для тестирования
/*
  + ...mapActions("Builder", ["resetBuilder"]),
  + ...mapActions("Cart", [
  +   "query",
  +   "createPizza",
  +   "updatePizza",
  + ]),

  +  ...mapActions("Auth", ["queryAddresses", "newAddresses"]),
  +  ...mapActions("Orders", ["newOrder"]),
*/

// Данные из тест хранилища
/*
  ...mapState("Auth", {
    user: (state) => state.user,
  }),
  ...mapState("Builder", {
    composition: (state) => state.composition,
  }),
  ...mapState("Cart", {
    pizzas: (state) => state.pizzas,
    misc: (state) => state.misc,
    address: (state) => state.address,
    recipient: (state) => state.recipient,
    phone: (state) => state.phone,
  }),
 */`

2022-05-03 11:39 UTC, Djaler commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Auth.newAddresses).toHaveBeenCalled();
Тут будут тестироваться не отдельные элементы, а в совокупности в основных сценариях

1) Создание заказа на новый адрес - тут мы проверяем корректность вызова newOrder, но попутно ещё косвенное проверяем получение данных из модуля корзины и т.д.
2) Создание заказа на существующих адрес - тут мы попутно проверяем получение данных из модуля адресов (так как, чтобы выбрать адрес, он должен быть доступен в селекте)
3) Отдельно можно проверить вызов экшенов загрузки данных - queryAddresses, query из Cart

2022-05-03 12:03 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Auth.newAddresses).toHaveBeenCalled();
Как проверить корректность вызова экшена newOrder??? Смотрела пример тут https://lmiller1990.github.io/vue-testing-handbook/ru/vuex-actions.html#%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-%D1%82%D0%B5%D1%81%D1%82%D0%B0, но ничего не выходит.

`let url = '';
let body = {};
let mockError = false;

jest.mock('axios', () => ({
  post: (_url, _body) => { 
    return new Promise((resolve) => {
      if (mockError) 
        throw Error("Mock error")

      url = _url
      body = _body
      resolve(true)
    })
  }
}));

it ('calls newOrder action', async () => {
      authenticateUser(store);
      createPizza(store);
      createComponent({ localVue, store, stubs });

      const commit = jest.fn();
      const order = {
        userId: null,
        phone: "",
        pizzas: [],
        misc: [],
        address: {
          id: null,
          name: `ул., д., кв.`,
          street: "",
          building: "",
          flat: "",
          comment: "",
        }
      };

      await actions.Orders.newOrder({ commit }, { order })

      expect(url).toBe("/api/orders")
      expect(body).toEqual({ order })
      expect(commit).toHaveBeenCalledWith(
        ADD_ENTITY, true
      )
    });`
    
    [https://skr.sh/sDlJilgw5QW?a](url)

2022-05-03 12:03 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Auth.newAddresses).toHaveBeenCalled();
https://skr.sh/sDlJilgw5QW?a скриншот

2022-05-03 20:55 UTC, Djaler commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Auth.newAddresses).toHaveBeenCalled();
Не, это ты пытаешься тестировать сам экшен, нам это тут не нужно. Мы проверяем, что компонент вызывает экшен правильно, т.е., с правильными аргументами.
Это нужно делать именно так, как ты делала с экшеном newAddress:
`expect(actions.Auth.newOrder).toHaveBeenCalledWith(expect.anything(), {тут ожидаемый объект, с которым экшен должен вызваться});`
Только не забудь предварительно добавить мок этого экшена в beforeEach

2022-05-04 07:38 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Auth.newAddresses).toHaveBeenCalled();
newAddress я не осилила, он так и не работает, там ошибка `Cart › calls newAddresses action

    expect(jest.fn()).toHaveBeenCalled()

    Expected number of calls: >= 1
    Received number of calls:    0`
    Можешь показать на моем newAddress или newOrder как проверить, что экшен вызывается с правильными аргументами?

2022-05-04 08:33 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Auth.newAddresses).toHaveBeenCalled();
У меня в тесте "calls newAddresses action" проблема: я выбираю вариант доставки на новый адрес
`const options = wrapper.find('.select').findAll('option');
      await options.at(1).setSelected();
      expect(wrapper.find('option:checked').element.value).toBe('new');`
Новый адрес выбран, но форма ввода адреса не открывается, почему????

2022-05-04 18:20 UTC, Djaler commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Auth.newAddresses).toHaveBeenCalled();
Потому что у тебя состояние формы меняется тоже в сторе. Селект выбора типа доставки привязан к computed'у recipientOrder, в сеттере которого дергается экшен updateUserRecipient и другие.
Собственно, так как экшены у нас в тестах замоканы, в итоге это изменение в селекте не вносит изменение в стор, соответственно геттер этого компьютеда (`return this.recipient`) возвращает всё то же значение, что и раньше.
По-хорошему бы тут, конечно, упростить логику, потому что слишком много всего происходит в этом сеттере, но если оставлять так, то твои шаги тут следующие:

1. В отдельном тесте проверять, что при выборе пункта в селекте дёргается ожидаемый экшен (updateUserRecipient).
2. А уже непосредственно в тесте про отправку заказа вместо работы с селектом таки подставить данные в стор вручную (мутацией)

2022-05-04 18:22 UTC, Djaler commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Auth.newAddresses).toHaveBeenCalled();
Ну а проверка правильности вызова экшена - например, как-то так:
```
expect(actions.Auth.updateUserRecipient).toHaveBeenCalledWith(expect.anything(), { recipient: 'new' }); 
```

2022-05-05 11:16 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Auth.newAddresses).toHaveBeenCalled();
Проверяю первое
`В отдельном тесте проверять, что при выборе пункта в селекте дёргается ожидаемый экшен (updateUserRecipient).`
и получаю ошибку
`Cart › calls newAddresses action
 expect(jest.fn()).toHaveBeenCalledWith(...expected)
 Expected: Anything, {"recipient": "new"}
 Number of calls: 0`
https://skr.sh/sDnTdtA5TOz?a (скриншот ошибки)

2022-05-05 11:17 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Auth.newAddresses).toHaveBeenCalled();
Что не так я написала?

2022-05-05 17:15 UTC, Djaler commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Auth.newAddresses).toHaveBeenCalled();
Так а ты перед проверкой вызова updateUserRecipient дёргаешь сам селект? В коде я этого не вижу. Ты сразу после создания компонента делаешь проверку

2022-05-08 12:04 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Auth.newAddresses).toHaveBeenCalled();
https://skr.sh/sDqq2zPbGnO

Опять двадцать пять - с чего начала, на том и осталась... ((( Не работает. Как нужно дергать селект?

2022-05-08 12:20 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Auth.newAddresses).toHaveBeenCalled();
Сорри! Вызвала addNewAddress(store) после создания компонента и тест завершился удачей!

2022-05-20 18:48 UTC, Djaler commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Cart.updateUserAddress).toHaveBeenCalledWith(
состояние полей адреса не меняется, потому что они привязаны к данным в сторе. Меняются эти данные при вызове экшена updateUserAddress, а экшен у тебя замокан. Ты можешь проверять вызов этого экшена вместе с вызовом updateUserRecipient в тесте выше. А в этом тесте - задавать в сторе нужные данные через мутации, а сам селект уже не трогать

2022-05-20 18:50 UTC, Djaler commented
Насчёт теста дочерних компонентов страниц - ну давай протестируем какой-нибудь один, и там будем использовать shallowMount. Чтоб было представление, как работать с заглушками компонентов

2022-05-21 10:44 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Cart.updateUserAddress).toHaveBeenCalledWith(
Хорошо, строки с селектом убираю. А разве я не добавила мутацией сохраненный адрес вот так:
`saveAddress(store);`
где saveAddress(store):
`const saveAddress = store => {  
  store.commit(
    SET_ENTITY,
    {
      module: "Auth",
      entity: "addresses",
      value: savedAddresses,
    }
  );
};`
или не туда добавила?..

2022-05-21 10:54 UTC, Djaler commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Cart.updateUserAddress).toHaveBeenCalledWith(
это ты заполнила данные о существующих адресах в модуле Auth. Но состояние формы ввода адреса у тебя ж хранится в модуле Cart. И заполняется оно с помощью мутации UPDATE_USER_ADDRESS

2022-05-21 10:59 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Cart.updateUserAddress).toHaveBeenCalledWith(
Да, уже поняла проблему. А что тогда остается в этом тесте? Проверить, что после мутации адреса и клика по кнопке Оформить заказ будет вызван 
`expect(actions.Orders.newOrder).toHaveBeenCalledWith(
  expect.any(Object), // The Vuex context
  {
   ...order,
   }
    );`
?

2022-05-21 11:06 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Cart.updateUserAddress).toHaveBeenCalledWith(
Или 
`expect(actions.Orders.newOrder).toHaveBeenCalled();`

Но почему-то не проходит даже это. 
`expect(jest.fn()).toHaveBeenCalledWith(...expected)
Number of calls: 0`

2022-05-21 11:44 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Cart.updateUserAddress).toHaveBeenCalledWith(
Скрин ошибки https://skr.sh/sE3DeSsA0pu

2022-05-21 20:01 UTC, Djaler commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Cart.updateUserAddress).toHaveBeenCalledWith(
Судя по всему, вот тут описана та же проблема, что и у тебя https://stackoverflow.com/questions/53382235/trigger-form-submit-on-button-click-in-vue-unit-test
Проблема в том, что по умолчанию монтируемый компонент не подключен к document, поэтому клик на кнопку с type="submit" не приводит к сабмиту формы. В доке про это всколзь упоминается https://test-utils.vuejs.org/guide/essentials/forms.html#triggering-complex-event-listeners
Решается это с помощью attachTo к предварительно созданному элементу

2022-05-22 10:32 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Cart.updateUserAddress).toHaveBeenCalledWith(
А куда вставлять создание div#root: внутри discribe или выше? Я вставила выше discribe после иных констант и внутрь discribe
`const div = document.createElement('div');
div.id = 'root';
document.body.appendChild(div);`
Потом в createComponent вставила attachTo
`const createComponent = options => {
      wrapper = mount(Cart, {
        attachTo: '#root',
        options,
      });
    };`
И посыпалась гора ошибок https://skr.sh/vE4vuxyNNTo?a
Как правильно это сделать?

2022-05-22 10:40 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Cart.updateUserAddress).toHaveBeenCalledWith(
Попробовала еще вынести внутрь теста attachTo
`it ('calls newOrder action', async () => {
      authenticateUser(store);
      createPizza(store);
      saveAddress(store);
      // createComponent({ localVue, store, stubs });
      wrapper = mount(Cart, {
        attachTo: document.getElementById('root'),
        localVue,
        store,
        stubs,
      });
      ...`
Получила ошибку https://skr.sh/sE4UtfABWqj (скрин)

2022-05-22 17:39 UTC, Djaler commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Cart.updateUserAddress).toHaveBeenCalledWith(
`mount(Cart, { ...options, attachTo: '#root' });`
А само создание div можно на самом верхнем уровне сделать, в принципе

2022-05-22 19:18 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Cart.updateUserAddress).toHaveBeenCalledWith(
[Vue warn]: Cannot find element: #root

2022-05-22 19:20 UTC, Djaler commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Cart.updateUserAddress).toHaveBeenCalledWith(
Точно вот это сделала?
![image](https://user-images.githubusercontent.com/7964583/169712250-0066a794-1f46-4e9d-a785-7a56a458d706.png)

Можешь запушить текущий вариант

2022-05-22 19:49 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Cart.updateUserAddress).toHaveBeenCalledWith(
Залила

2022-05-22 20:13 UTC, Djaler commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Cart.updateUserAddress).toHaveBeenCalledWith(
Так, ну с самим сабмитом формы проблемы уже нет. Метод вызывается.
Ошибка `Cannot read properties of undefined (reading 'id')` в `this.user.id`. user у тебя тянется из модуля Auth стора, значит ты в тесте не закинула эти данные в сторе предварительно

2022-05-23 05:50 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Cart.updateUserAddress).toHaveBeenCalledWith(
Странно, ведь в тесте вызывается authenticateUser(store); (в helpers.js закидываются данные юзера, которые берутся из static/user.json). Там не было id, я добавила. Ошибка не ушла. Может проблема с контекстом this? Скриншот https://skr.sh/sE5pfrpPl8W?a

2022-05-23 06:51 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Cart.updateUserAddress).toHaveBeenCalledWith(
Почему-то стор Auth.user пуст... console.log(store.state.Auth.user); отдает underfined

2022-05-23 07:04 UTC, romanovaviktoriya commented on src/frontend/src/views/__tests__/Cart.spec.js
> +      expect(actions.Cart.updateUserAddress).toHaveBeenCalledWith(
Вроде исправила

2022-06-08 21:28 UTC, Djaler commented
1.  Нет, саму загрузку данных в тесте компонента проверять не нужно, так как он не знает ничего, откуда эти данные берутся, он просто берет их из стора. Ну в целом - основные вещи проверены. Учитывая, что дочерние компоненты тестируются отдельно.
2.  Да, выглядит правильно
3. Проп checked у RadioButton заполняется с помощью v-model, в BuilderDoughSelector он берется из компьютеда checkedDough, который берет значение из state.composition.dough.value. Выходит, там это значение почему-то undefined. А undefined оно потому что вот эта подготовка данных неправильная:
```
const setDough = (store) => {
  store.commit(
    SET_ENTITY,
    {
      module: "Builder",
      entity: "dough",
      value: dough,
    },
  );
};
```
В этом модуле у тебя же лежат данные о выбранном тесте в composition.dough. И заполняются они мутацией CHANGE_DOUGH
4. Нет, необязательно, такого правила нет. Просто если использовать mount - то такие тесты более устойчивы к изменению реализации компонента. Например, мы можем его часть выделить в отдельный компонент, а тест продолжит работать, поскольку тестирует всё в совокупности. А с shallowMount, с другой стороны, проще в том плане, что мы можем тестировать компонент в изоляции от его дочерних. Например, есть у тебя компонент Foo, который внутри себя в цикле выводит компоненты Bar. И тестируя компонент Foo через shallowMount - мы можем просто проверить, что вывелось нужное количество Bar и им в пропсы передались правильные данные. А что там внутри Bar происходит - нам тут совсем не важно, мы его протестируем отдельно. Лично я практически всегда предпочитаю использовать именно shallowMount. К слову, использовать shallowMount с компонентом, у которого нет дочерних - просто не имеет смысла, потому что shallowMount предназначен для автоматического создания заглушек дочерних компонентов.
5. Да, тестирование - это последнее обязательное задание

2022-06-09 10:53 UTC, romanovaviktoriya commented
Пытаюсь подчистить  stubs в тестах с mount, но уже дважды начинали сыпаться ошибки в Cart.spec.js & Index.spec.js. Почему? Скрин https://skr.sh/sEMV4jzTndX

2022-06-23 13:25 UTC, Djaler commented on src/frontend/src/views/__tests__/Popup.spec.js
> +    await close.trigger('click');
ты права, тут все дело в том, что в тестах анимация не выполняется

единственное, что тут можно сделать - вручную сэмулировать то, элемент кидает событие animationend

2022-06-23 13:33 UTC, Djaler commented on src/frontend/src/modules/profile/components/__tests__/ProfileAddressEdit.spec.js
> +    expect(wrapper.find('[data-test="name"] input').element.value).toBe(propsData.adr.name);
я бы тут проверял не value инпута, который где-то внутри, а просто проп value самого компонента AppInput

2022-06-23 14:59 UTC, romanovaviktoriya commented
1) Popup.spec.js (тут видимо связано с анимацией). Как сэмулировать событие анимации?

2) ProfileAddressEdit.spec.js (тут не пойму, как в компонент формы передать не все поля, и увидеть что из-за невалидности формы на кнопку Сохранить вешается атрибут disabled, возможно опять же дело в vee-validate)?

3) Плюс проблема в тесте Profile.spec.vue с подключением статических файлов посредством require(). Решения нашла тут https://github.com/facebook/jest/issues/2663 Самый простой способ решения?

2022-06-23 15:02 UTC, Djaler commented on src/frontend/src/modules/profile/components/__tests__/ProfileAddressEdit.spec.js
> +    expect(submit.attributes('disabled')).toBe('disabled');
тут дело вот в чём - vee-validate запускает валидацию асинхронно и обновляет состояние раз в 16мс , поэтому тут во-первых, нужно подождать завершения промисов, а во-вторых, дождаться обновления состояния (https://vee-validate.logaretm.com/v3/advanced/testing.html#testing-validationobserver-debounced-state)

2022-06-23 15:06 UTC, Djaler commented on src/frontend/src/modules/profile/components/__tests__/ProfileAddressEdit.spec.js
> +    await name.trigger('input');
можно использовать https://v1.test-utils.vuejs.org/api/wrapper/setvalue.html#setvalue

2022-06-23 15:09 UTC, romanovaviktoriya commented
Боже, я только что закрыла пуллреквест?! Как это исправить?

2022-06-23 15:26 UTC, romanovaviktoriya commented
А как быть с подключением статических файлов посредством require()?

2022-06-23 17:27 UTC, Djaler commented on src/frontend/jest.config.js
> +    ".+\\.(css|styl|less|sass|scss|svg|png|jpg|ttf|woff|woff2)$":
вот сюда нужно добавить ещё webp, чтоб импорт таких файлов в тестах подменялся на заглушку

2022-06-23 17:30 UTC, Djaler commented
> 1. Popup.spec.js (тут видимо связано с анимацией). Как сэмулировать событие анимации?

найти элемент и на нём сделать `trigger('animationend')`

2022-06-23 17:31 UTC, Djaler commented
Я думаю, ты можешь добить эти тесты и на этом остановиться, другие страницы не делать. Чтоб успеть защититься

2022-06-23 19:11 UTC, romanovaviktoriya commented
А так можно? Тогда Profile.spec.js получается удалить (с require() не разобралась)?

2022-06-23 19:22 UTC, romanovaviktoriya commented
> trigger('animationend')

Не все так просто... https://skr.sh/sEaavsELDPG

2022-06-26 11:26 UTC, Djaler commented
1) Profile.spec.js А как быть с подключением статических файлов посредством require()?

Эта проблема же решилась добавлением расширения webp в список для jest-transform-stub, разве нет?

2022-06-26 11:28 UTC, Djaler commented
А если ты о том, как протестировать вывод этого изображения - не думаю что это нужно. Это статическое изображение, тут нет логики которую надо проверять

2022-06-26 11:31 UTC, romanovaviktoriya commented
Эта проблема же решилась добавлением расширения webp в список для jest-transform-stub, разве нет? Ушла... Не буду трогать изображение. )) Спасибо

2022-06-26 11:31 UTC, romanovaviktoriya commented
У меня сыпятся ошибки в Popup.spec.js

2022-06-26 11:44 UTC, Djaler commented
Ошибка из-за того, что не выполняется метод enter. enter у тебя дёргается по событию enter у transition. А в тестах этого не происходит, потому что transition автоматически стабается. Чтобы это отключить, нужно передать в опциях компонента соответствующий флаг
`createComponent({ localVue, store, stubs: { transition:false } });`

2022-06-26 11:45 UTC, Djaler commented
После этого там остаётся ещё ошибка при вызове router.push, это надо поправить, подключив роутер в тестах или замокав его

2022-06-26 11:48 UTC, romanovaviktoriya commented
[https://skr.sh/sEdg9ykVPin](url) а что это за ошибка, подскажешь? Или это не критично?

2022-06-26 11:51 UTC, Djaler commented
Это где-то у тебя в тесте дёргается асинхронная функция и в этой функции падает ошибка. При этом ошибка никак не обрабатывается

2022-06-26 11:53 UTC, Djaler commented
Надо смотреть, возможно дёргается какой-то незамоканный экшен и он пытается отправить запрос, например

2022-06-26 12:18 UTC, romanovaviktoriya commented
Закоментировав по очереди тесты, выяснила, что ошибка в файле Profile.spec.js.

2022-06-26 16:15 UTC, merged